"""Client portal export (C24) — a static, offline-browsable HTML bundle.

One self-contained page: exec summary, findings table with evidence,
timeline. No JS dependencies, no server — email it or drop it on a
share. Written to outputs/portal/<engagement>.html.
"""

from __future__ import annotations

import html
from pathlib import Path


def export_portal(findings: list, engagement: str = "engagement", meta: dict | None = None) -> Path:
    from suijin.modules.platform.lib.workspace import artifact_dir
    from suijin.modules.tools.lib.report_templates import render

    meta = meta or {}
    d = artifact_dir("portal")
    d.mkdir(parents=True, exist_ok=True)
    out = d / f"{''.join(c if c.isalnum() or c in '-_' else '_' for c in engagement)[:50]}.html"

    exec_html = html.escape(render(findings, engagement, "exec"))
    tech_html = html.escape(render(findings, engagement, "technical"))
    rows = []
    sev_color = {"critical": "#c0392b", "high": "#d35400", "medium": "#f39c12", "low": "#7f8c8d"}
    for f in findings or []:
        rows.append(
            f"<tr><td style='color:{sev_color.get(str(f.get('severity', 'low')).lower(), '#333')};font-weight:bold'>{html.escape(str(f.get('severity', '?')))}</td>"
            f"<td>{html.escape(str(f.get('type', '?')))}</td>"
            f"<td>{html.escape(str(f.get('confidence', '?')))}</td>"
            f"<td><code>{html.escape(str(f.get('evidence', ''))[:200])}</code></td></tr>"
        )
    page = f"""<!doctype html><html><head><meta charset="utf-8"><title>Suijin — {html.escape(engagement)}</title>
<style>body{{font-family:system-ui;margin:2rem;max-width:60rem;background:#0e1116;color:#d7dee8}}
h1,h2{{color:#8be9fd}} pre{{background:#161b22;padding:1rem;border-radius:8px;white-space:pre-wrap}}
table{{border-collapse:collapse;width:100%}} td,th{{border:1px solid #2d333b;padding:.5rem;text-align:left}} th{{background:#161b22}}
code{{color:#ff79c6}}</style></head><body>
<h1>Suijin Assessment — {html.escape(engagement)}</h1>
<pre>{exec_html}</pre>
<h2>Findings</h2>
<table><tr><th>Severity</th><th>Type</th><th>Confidence</th><th>Evidence</th></tr>{"".join(rows) or "<tr><td colspan=4>No findings</td></tr>"}</table>
<h2>Technical Detail</h2>
<pre>{tech_html}</pre>
<p style="color:#7f8c8d">Generated by Suijin — offline static export; no external requests.</p>
</body></html>"""
    out.write_text(page, encoding="utf-8")
    return out
